### ISSUE TITLE
how to run

### ISSUE THREAD

**Issue by hobrin** [alexbie98/MazeGame#1]
doesn't run because of this:
```
Exception in thread "Thread-0" java.lang.Error: Unresolved compilation problems: 
        GLFW cannot be resolved
        GLFW cannot be resolved to a variable
        GLFW cannot be resolved

        at main.GameThread.run(GameThread.java:58)
        at java.base/java.lang.Thread.run(Thread.java:829)
```
visual studio code on ubuntu

can't find installation instructions so yea

**Comment by hobrin** [comment]
Ah I got it to work in IntelliJ. GLFW was missing, download zip here https://www.lwjgl.org/customize, put it in a folder called 'lib' and then run it. There were some errors with the if statements, but those are specific and really easy to solve.
